booking/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # auth
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),

    # bookings
    path('book-table/', views.book_table, name='book-table'),
    path('user-bookings/', views.user_bookings, name='user-bookings'),
    path('get-booking/<int:id>/', views.get_booking, name='get-booking'),
    path(
        'update-booking/<int:id>/', views.update_booking, name='update-booking'
        ),
    path(
        'cancel-booking/<int:id>/',
        views.cancel_booking,
        name='cancel-booking'),
    ]

menu/urls.py
from django.urls import path
from . import views


urlpatterns = [
    # This will map the root URL to the home view
    path('', views.home_view, name='home'),
    path('menu', views.menu_view, name='menu'),
]

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('menu.urls')),
    path("accounts/", include("allauth.urls")),
    path(
        'login/', auth_views.LoginView.as_view(
            template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('booking/', include('booking.urls')),
]

booking/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


class Table(models.Model):
    """
    Model representing a table with a specific capacity.
    Orders tables by descending capacity.
    """
    capacity = models.IntegerField()

    class Meta:
        ordering = ('-capacity',)

    def __str__(self):
        return f"Table Capacity: {self.capacity}"


class Booking(models.Model):
    """
    Model representing a booking.
    Includes fields for user, table, date, time, and number of guests.
    """
    GUESTS_CHOICES = [(1, 1), (2, 2), (3, 3), (4, 4),
                      (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='bookings')
    table = models.ForeignKey(
        Table, on_delete=models.CASCADE, related_name='bookings')
    date = models.DateField()
    time = models.TimeField()
    guests = models.IntegerField(
        choices=GUESTS_CHOICES,
        default=1,
        validators=[
         MaxValueValidator(10),
         MinValueValidator(1)
        ]
    )

    def __str__(self):
        return f"Booking for {self.user.username.capitalize()} on {
            self.date} at {self.time} for {self.guests} guests"

booking/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Booking

import datetime


class UserRegistrationForm(UserCreationForm):
    """
    A form for user registration, inherits from UserCreationForm.
    Specifies the fields: username, email, password1, and password2.
    """
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class CustomLoginForm(AuthenticationForm):
    """
    A custom login form with placeholder attributes for username and password.
    Defines the fields: username and password with their respective widgets.
    """
    username = forms.CharField(max_length=150, widget=forms.TextInput(
        attrs={'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Password'}))


class BookingForm(forms.ModelForm):
    """
    A form for booking, including date, time, and number of guests.
    Ensures date is today or later, and time is between opening and closing.
    """
    today = datetime.date.today()
    opening_time = datetime.time(11, 0)
    closing_time = datetime.time(23, 0)
    date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date', 'min': today}),
        label='Booking Date'
    )
    time = forms.TimeField(
        widget=forms.TimeInput(
            attrs={'type': 'time', 'min': opening_time, 'max': closing_time}),
        label='Booking Time'
    )

    class Meta:
        model = Booking
        fields = ['date', 'time', 'guests']

    def clean_date(self):
        # additional layer of security, can't select if date is in past
        date = self.cleaned_data['date']
        if date < datetime.date.today():
            raise forms.ValidationError("Booking date cannot be in the past.")
        return date

    def clean_time(self):
        # defining when restaurant is open
        time = self.cleaned_data['time']
        opening_time = datetime.time(11, 0)
        closing_time = datetime.time(22, 0)
        if not (opening_time <= time < closing_time):
            raise forms.ValidationError(
                "Booking time must be within 11:00 AM - 9:59 PM")
        return time

booking/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import JsonResponse
from datetime import datetime, date, time
from .forms import UserRegistrationForm, CustomLoginForm, BookingForm
from .models import Table, Booking
from .utils import find_available_table
import time as time_control
from django.contrib import messages


def register(request):
    """
    Handles user registration. If the request method is POST, it processes
    the form and registers the user if valid. Upon successful registration,
    logs the user in and redirects to the 'book-table' page.
    Renders the registration form if the request method is GET.
    """
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(
                request, 'Registration successful! Welcome to East flavore')
            return redirect('/')
        else:
            messages.error(
                request, 'Registration failed. Please check the form again.')
    else:
        form = UserRegistrationForm()
    return render(request, 'booking/register.html', {'form': form})


def user_login(request):
    """
    Handles user login. Processes the login form if the request method is POST,
    authenticates the user, and logs them in if credentials are valid.
    Redirects to the 'book-table' page upon successful login.
    Renders the login form if the request method is GET.
    """
    if request.method == 'POST':
        form = CustomLoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f"Welcome back, {username}!")
                return redirect('book-table')
        else:
            messages.error(request, "Invalid username or password.")
    else:
        form = CustomLoginForm()
    return render(request, 'booking/login.html', {'form': form})


@login_required
def user_logout(request):
    logout(request)
    messages.success(request, "You have successfully logged out!")
    return redirect('home')


# BOOKING
@login_required
def book_table(request):
    """
    Handles table booking for logged-in users.
    On POST, processes the booking form, finds an available table,
    and creates a booking or shows an error if no table is available.
    """
    if request.method == 'POST':
        form = BookingForm(request.POST)
        print(form.data)
        if form.is_valid():
            date = form.cleaned_data['date']
            time = form.cleaned_data['time']
            guests = form.cleaned_data['guests']

            tzname = request.COOKIES.get("django_timezone", "UTC")

            # Check if the selected date/time is in the past
            current_datetime = datetime.now()
            selected_datetime = datetime.combine(date, time)

            if selected_datetime < current_datetime:
                messages.error(
                    request,
                    "Booking time must be at least"
                    "-one minute ahead of the current time!")
                return render(
                    request, 'booking/book_table.html', {'form': form})

            # Find available table for the given date, time, guests
            table = find_available_table(
                date, time, guests, request.user, tzname)

            if table:
                # Create the booking if an available table is found
                booking = Booking.objects.create(
                    user=request.user,
                    table=table,
                    date=date,
                    time=time,
                    guests=guests
                )
                messages.success(
                    request, 'Your booking is successful!')
                return redirect(reverse('user-bookings'))
            else:
                # No available table found, show an error message
                form.add_error(
                    None,
                    (
                        "Sorry, no table available for the selected date,"
                        "time, and guests, or you have booked table already in this hour!"
                        ))

    else:
        form = BookingForm()
    return render(request, 'booking/book_table.html', {'form': form})


@login_required
def user_bookings(request):
    """
    Retrieves all bookings made by the logged-in user and
    renders them in a template.
    """
    bookings = Booking.objects.filter(user=request.user)
    context = {'bookings': bookings}
    return render(request, 'booking/bookings.html', context)


@login_required
def cancel_booking(request, id):
    """
    Cancels a booking for the logged-in user based on the booking ID.
    Returns a success message if the booking is found and canceled.
    Returns an error if the booking is not found or the user has no permission.
    """
    booking = Booking.objects.filter(user=request.user, id=id)
    if booking.exists():
        booking.delete()
        response_data = {'message': "Booking canceled successfully!"}
        messages.error(request, 'Booking canceled successfully')
        return JsonResponse(response_data, status=200)
    else:
        messages.error(request, 'Booking not found')
        return JsonResponse(
            {
                'error': "Booking not found"
                "or you don't have permission to cancel it."
                       },
            status=404)


@login_required
def get_booking(request, id):
    """
    get specific booking
    """
    booking = get_object_or_404(Booking, id=id)
    return render(
        request,
        'booking/edit_book.html',
        {'booking': booking, 'get_range': range(1, 11)}
        )


@login_required
def update_booking(request, id):
    booking = get_object_or_404(Booking, id=id)

    if request.user != booking.user:
        messages.error(request, 'Invalid user!')
        return redirect(reverse('login'))

    if request.method == 'POST':
        date_str = request.POST.get('date')
        time_str = request.POST.get('time')
        guests = request.POST.get('guests')
        _date = datetime.strptime(date_str, "%Y-%m-%d").date()
        _time = datetime.strptime(time_str, "%H:%M").time()
        _guests = int(guests)

        current_time_str = time_control.strftime(
            "%H:%M", time_control.localtime())
        current_time = datetime.strptime(current_time_str, "%H:%M").time()

        if _date and _time and _date == date.today() and _time > current_time :
            booking.date = _date
            booking.time = _time
            
        if _date and _time and _date == date.today() and _time <= current_time :
            messages.error(request, 'Invalid time!')
            return render(
                request,
                'booking/edit_book.html', {
                    'booking':booking, 'get_range':range(1,11)})
        else:
            if _date and _date >= date.today():
                booking.date = _date
            else:
                messages.error(request, 'Invalid date!')
                return render(
                    request,
                    'booking/edit_book.html',
                    {'booking': booking, 'get_range': range(1, 11)})

            if _time and (time(11, 0) <= _time < time(22, 0)):
                booking.time = _time
            else:
                messages.error(request, 'Invalid time!')
                return render(
                    request,
                    'booking/edit_book.html',
                    {'booking': booking, 'get_range': range(1, 11)})

            if _guests and 11 > _guests > 0:
                booking.guests = _guests
            else:
                messages.error(request, 'book for guests from 1 to 10!')
                return render(
                    request,
                    'booking/edit_book.html',
                    {'booking': booking, 'get_range': range(1, 11)})
        booking.save()
        messages.success(request, 'Booking updated successfully!')
    return redirect(reverse('user-bookings'))

booking/templates/booking/book_table.html
{% extends 'base.html' %} {%load static%} {% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/book-table.css' %}"
/>
{% endblock head %} {% block content %}
<div class="book-table-wrapper">
  <div class="image">
    <h1>5-star service!</h1>
    <img
      src="{% static 'img/book.jpg' %}"
      id="restaurant-image"
      alt="Restaurant dining area"
    />
  </div>
  <div class="inner-wrapper">
    <h2 id="headline">Book a Table</h2>
    <p id="alert">Restaurant works between 11 AM and 11 PM.</p>
    <!--{% if form.non_field_errors %}
    <div class="error">{{ form.non_field_errors }}</div>
    {% endif %}-->

    <form method="post" class="book-table-form">
      {% csrf_token %} {{ form.as_p }}
      <p>Booking time must be within 11:00 AM - 9:59 PM.</p>
      <button type="submit" class="book-button">Book Now</button>
    </form>
  </div>
</div>
{% endblock %}

booking/templates/booking/bookings.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bookings.css' %}" />
{% endblock head %} {% block content %}
<div class="bookings-wrapper">
  <h1 id="heading">My bookings</h1>
  <div class="bookings">
    <div class="booking-buttons">
      <a href="{% url 'book-table' %}" class="add-booking">Add booking</a>
    </div>
    {% for booking in bookings %}
    <div class="booking" data-bookingId="{{booking.id}}">
      <!-- I put span here so booking info is in center because of space-between property  -->
      <!-- <span></span> -->
      <p>{{booking}}</p>

      <!-- I added a styled anchor tag for the Add Booking link -->
      <div class="booking-buttons">
        <a
          href="{% url 'get-booking' booking.id %}"
          class="add-booking edit-button"
          >Edit booking</a
        >
        <button class="cancel-booking">Cancel booking</button>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<!-- JavaScript includes -->
<script
  async
  src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"
></script>
<script defer src="{% static 'js/bookings.js' %}"></script>
{% endblock %}

booking/templates/booking/edit_book.html
{% extends 'base.html' %} {%load static%} {% block head %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/book-table.css' %}"
>
{% endblock head %} {% block content %}
<div class="book-table-wrapper">
  <div class="image">
    <h1>5-star service!</h1>
    <img
      src="{% static 'img/book.jpg' %}"
      id="restaurant-image"
      alt="Restaurant dining area"
    >
  </div>
  <div class="inner-wrapper">
    <h2 id="headline">Change Your Booking</h2>
    <p id="alert">Restaurant works between 11 AM and 11 PM.</p>
    <form method="post" action="{% url 'update-booking' booking.id %}" class="book-table-form">
        {% csrf_token %}
          <p>
              <label for="id_date">Booking Date:</label>
              <input type="date" name="date" value="{{booking.date|date:'Y-m-d'}}" required id="id_date">
          </p>
          <p>
              <label for="id_time">Booking Time:</label>
              <input type="time" name="time" value="{{booking.time|time:'H:i'}}" required id="id_time">
              <p>Booking time must be within 11:00 AM - 9:59 PM.</p>
          </p>
          <p>
            <label for="id_guests">Guests:</label>
            <select name="guests" class="form-control" id="id_guests">
                {% with "12345678910" as numbers %}
                    {% for i in get_range %}
                        <option value="{{ i }}" {% if booking.guests == i|add:0 %}selected{% endif %}>{{ i }}</option>
                    {% endfor %}
                {% endwith %}
            </select>
        </p>
        <button type="submit" class="book-button">Done</button>
    </form>
  </div>
</div>
{% endblock %}    

booking/templates/booking/login.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock head %} {% block content %}
<div class="login-wrapper">
  <div class="image">
    <h1>Best meals in town!</h1>
    <img src="{% static 'img/book.jpg' %}" id="restaurant-image" alt="Restaurant dining area">
  </div>
  <div class="inner-wrapper">
    <h2 id="headline">Login</h2>
    <form method="post" class="login-form">
      {% csrf_token %} {{ form.as_p }}
      <p id="register-link">
        Don't have an account? <a href="{% url 'register' %}">Register</a>
      </p>
      <button type="submit" class="login-button">Login</button>
    </form>
  </div>
</div>
{% endblock %}

booking/templates/booking/make_reservation.html
{% extends 'base.html' %}

{% block content %}
  <h2>Make a Reservation</h2>
  <form method="POST">
    {% csrf_token %}
    <label for="date">Date:</label>
    <input type="date" name="date" required>
    
    <label for="time">Time:</label>
    <input type="time" name="time" required>
    
    <label for="guests">Number of Guests:</label>
    <input type="number" name="guests" required>
    
    <button type="submit">Submit</button>
  </form>
{% endblock %}

booking/templates/booking/regirter.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}" />
{% endblock head %}
{% block content %}
<div class="register-wrapper">
    <div class="inner-wrapper">
        <h2 id="headline">Register</h2>
        <form method="post" class="register-form">
            {% csrf_token %} {{ form.as_p }}
            <p id="login-link">Already a member? <a href="{% url 'login' %}">Login</a></p>
            <button type="submit" class="register-button">Login</button>
        </form>
    </div>
</div>
{% endblock %}

booking/templates/booking/register.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}">
{% endblock head %} {% block content %}
<div class="register-wrapper">
  <div class="inner-wrapper">
    <h2 id="headline">Register</h2>
    <form method="post" class="register-form">
      {% csrf_token %} {{ form.as_p }}
      <p id="login-link">
        Already a member? <a href="{% url 'login' %}">Login</a>
      </p>
      <button type="submit" class="register-button">Register</button>
    </form>
  </div>
</div>
{% endblock %}